AppEntrega/urls.py
from django.urls import path
from AppEntrega.views import *
from django.contrib.auth.views import LogoutView 

urlpatterns = [
    path("", inicio, name="inicio"),    
    path("login/", inicio_sesion, name="LOGIN"),
    path("recetas/", ver_recetas, name="Recetas"),
    path("registro/", registro, name="REGISTRO"),
    path("logout/", cerrar_sesion, name="Logout"),
    path("personalizarPerfil/", agregarAvatar, name="Avatar"),
    path("editarPerfil/", editarUsuario, name="EditarUsuario"),
    path("about/", About, name="about"),

    #CRUD DE RECETAS
    path("sugerencias/", sugerir, name="Hacer Sugerencia"),
    path("mis_sugerencias/", mis_sugerencias, name="Mis Sugerencias"),
    path("editarSugerencias/<nombreSugerencia>/", editarSugerencia, name="EditarSugerencia"),
    path("eliminarSugerencias/<nombreSugerencia>/", eliminarSugerencia, name="EliminarSugerencia"),


    #CRUD DE CONSULTAS
    path("crearConsulta/", crear_consulta, name="Crear mi Consulta"),
    path("verConsulta/", mi_consulta, name="Ver mi Consulta"),


]

ProyectoEntrega/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('AppEntrega/', include("AppEntrega.urls"))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AppEntrega/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Usuario(models.Model):
    nombre = models.CharField(max_length=60)
    apellido = models.CharField(max_length=60)
    email = models.EmailField()
    edad = models.IntegerField()

    def __str__(self):
        return f"Nombre: {self.nombre} {self.apellido} / Edad: {self.edad}"
    

class AddReceta(models.Model):
    nombre = models.CharField(max_length=60)
    nombre_receta = models.CharField(max_length=60, default="")
    sabor = models.CharField(max_length=60)
    cant_pasos = models.IntegerField()
    dificultad = models.CharField(max_length=60)
    descripcion = models.CharField(max_length=240, default='DEFAULT VALUE', blank=True, null=True)

    def __str__(self):
        return f"Nombre de la receta: {self.nombre} / Sabor: {self.sabor} / Cantidad de pasos: {self.cant_pasos} / Dificultad: {self.dificultad}"

class Consulta(models.Model):
    nombre = models.CharField(max_length=60)
    email = models.EmailField()
    consulta = models.CharField(max_length=60)

    def __str__(self):
        return f"Nombre: {self.nombre} / {self.email}"


class Avatar(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="avatares", null=True, blank=True)

AppEntrega/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from AppEntrega.models import Avatar


class UsuarioForm(forms.Form):
    nombre = forms.CharField(max_length=60)
    apellido = forms.CharField(max_length=60)
    email = forms.EmailField()
    edad = forms.IntegerField()
    
class UsuarioRegistro(UserCreationForm):

    email = forms.EmailField()
    password1 = forms.CharField(label = "Contraseña", widget=forms.PasswordInput)
    password2 = forms.CharField(label = "Repetir la contraseña", widget=forms.PasswordInput)

    class Meta:

        model = User 
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]

class EditarUsuario(UserChangeForm):

    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["email","first_name", "last_name"]


class AvatarForm(forms.ModelForm):

    class Meta:
        model = Avatar
        fields = ["imagen"]



class ConsulForm(forms.Form):
    nombre = forms.CharField(max_length=60)
    email = forms.EmailField()
    consulta = forms.CharField(max_length=240)

class RecetasForm(forms.Form):
    nombre = forms.CharField(max_length=60)
    nombre_receta = forms.CharField(max_length=60)
    sabor = forms.CharField(max_length=60)
    cant_pasos = forms.IntegerField()
    dificultad = forms.CharField(max_length=60)
    descripcion = forms.CharField(max_length=240)

AppEntrega/views.py
from django.shortcuts import render
from AppEntrega.models import *
from AppEntrega.forms import *
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required




# Create your views here.

# Inicio:

def inicio_sesion(request):

    if request.method == "POST":

        form = AuthenticationForm(request, data = request.POST)

        if form.is_valid():

            usuario = form.cleaned_data.get("username")
            passw = form.cleaned_data.get("password")

            user = authenticate(username = usuario, password = passw)

            if user:

                login(request, user)

                return render(request, "AppEntrega/inicio.html", {"mensaje":f"Bienvenido {user}!"})
            
        else:

            return render(request, "AppEntrega/inicio.html", {"mensaje":"Datos incorrectos."})
        
    else:

        form = AuthenticationForm()

    return render(request, "AppEntrega/login.html", {"formulario":form})
        
def registro(request):

    if request.method == "POST":

        form = UsuarioRegistro(request.POST)

        if form.is_valid():

            usuario = form.cleaned_data["username"]
            form.save()
            return render(request, "AppEntrega/inicio.html", {"mensaje":f"Usuario creado existosamente."})
        
    else:

        form = UsuarioRegistro()

    return render(request, "AppEntrega/registro.html", {"formulario":form})

@login_required
def agregarAvatar(request):

    if request.method == "POST":

        form = AvatarForm(request.POST, request.FILES)

        if form.is_valid():

            usuarioActual = User.objects.get(username=request.user)

            nuevo_avatar = Avatar(usuario=usuarioActual, imagen=form.cleaned_data["imagen"])

            nuevo_avatar.save()

            return render(request, "AppEntrega/inicio.html")
        
    else:

        form = AvatarForm()

    return render(request, "AppEntrega/agregarAvatar.html", {"formulario":form})

#Logout
@login_required
def cerrar_sesion(request):
    logout(request)
    return render(request,"AppEntrega/inicio.html", {"mensaje":"Has cerrado sesión"})

@login_required
def editarUsuario(request):

    usuario = request.user

    if request.method == "POST":

        form = EditarUsuario(request.POST)

        if form.is_valid():

            info = form.cleaned_data

            usuario.email = info["email"]
            usuario.first_name = info["first_name"]
            usuario.last_name = info["last_name"]

            usuario.save()

            return render(request, "AppEntrega/inicio.html")
        
    else:

        form = EditarUsuario(initial={
            "email":usuario.email,
            "first_name":usuario.first_name,
            "last_name":usuario.last_name,
        })

    return render(request, "AppEntrega/editarPerfil.html", {"formulario":form, "usuario":usuario})
  



def inicio(request):
    return render(request, "AppEntrega/inicio.html")

def About(request):
    return render(request, "AppEntrega/about.html")

#consultas

def crear_consulta(request):

    if request.method == "POST":
        formulario = ConsulForm(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            new_consul = Consulta(nombre = info["nombre"],
                                  email = info["email"],
                                  consulta = info["consulta"]
            )
        new_consul.save()
        return render(request, "AppEntrega/inicio.html")
    else:
        formulario = ConsulForm()
    
    return render(request, "AppEntrega/crearConsulta.html", {"formulario":formulario})

def mi_consulta(request):
    buscar = request.GET.get("nombre","")
    if buscar == "":
        return render(request, "AppEntrega/verConsulta.html")
    else:
        result = Consulta.objects.filter(nombre__icontains=buscar)
        return render(request, "AppEntrega/verConsulta.html", {"result":result})
    


#Sugerencias
    
def sugerir(request):
    if request.method == "POST":
        formulario = RecetasForm(request.POST)
        if formulario.is_valid():
            info = formulario.cleaned_data
            new_recipe = AddReceta(nombre = info["nombre"],
                                  nombre_receta = info["nombre_receta"],
                                  sabor = info["sabor"],
                                  cant_pasos = info["cant_pasos"],
                                  dificultad = info["dificultad"],
                                  descripcion = info["descripcion"]
            )
        new_recipe.save()
        return render(request, "AppEntrega/inicio.html")
    else:
        formulario = RecetasForm()
    
    return render(request, "AppEntrega/Sugerencias.html", {"formulario":formulario})

def mis_sugerencias(request):
    buscar = request.GET.get("nombre","")
    if buscar == "":
        return render(request, "AppEntrega/mis_sugerencias.html")
    else:
        result = AddReceta.objects.filter(nombre__icontains=buscar)
        return render(request, "AppEntrega/mis_sugerencias.html", {"result":result})
    

def eliminarSugerencia(request, nombreSugerencia):

    sugerencia = AddReceta.objects.get(nombre=nombreSugerencia)
    sugerencia.delete()

    sugerencias = AddReceta.objects.all()

    contexto = {"Recetas sugeridas":sugerencias}

    return render(request, "AppEntrega/elimnarSugerencias.html", contexto)

def editarSugerencia(request, nombreSugerencia):

    sugerencia = AddReceta.objects.get(nombre=nombreSugerencia)

    if request.method == "POST":

        miFormulario = RecetasForm(request.POST)

        if miFormulario.is_valid():

            info = miFormulario.cleaned_data

            sugerencia.nombre = info["nombre"]
            sugerencia.nombre_receta = info["nombre_receta"]
            sugerencia.sabor = info["sabor"]
            sugerencia.cant_pasos = info["cant_pasos"]
            sugerencia.dificultad = info["dificultad"]
            sugerencia.descripcion = info["descripcion"]

            sugerencia.save()

            return render(request, "AppEntrega/inicio.html")
        
    else:

        miFormulario = RecetasForm(initial={"nombre":sugerencia.nombre, "nombre_receta":sugerencia.nombre_receta, "sabor":sugerencia.sabor,
        "cant_pasos":sugerencia.cant_pasos, "dificultad":sugerencia.dificultad, "descripcion":sugerencia.descripcion})

    return render(request, "AppEntrega/editarSugerencias.html", {"miFormulario":miFormulario, "nombre":nombreSugerencia})    


#Recetas
    
def ver_recetas(request):
    return render(request, "AppEntrega/Recetas.html")

AppEntrega/templates/AppEntrega/Sugerencias.html
{% extends "AppEntrega/padre.html" %}


{% load static %}


{% block titulo %} Sugerencias {% endblock %}

{% block TituloPrincipal %} Sugerinos alguna receta! {% endblock %}

{% block subtitulo %} Aqui podras sugerirnos la receta que quieras para que forme parte de la lista! {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} 
<!-- Consultas Section-->
<section class="page-section" id="Consultas">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Sugerencias</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form action="/AppEntrega/sugerencias/" method="POST"> {% csrf_token %}

                    {{formulario}}
                    
                    <br>
                    <input type="submit" value:"Guardar" class="btn btn-primary btn-xl"><br>
                </form><br>
                <a class ="btn btn-primary btn-xl" href="{% url 'Mis Sugerencias' %}">Mostrar mi Sugerencia</a>

            </div>
        </div>
    </div>
</section>               
{% endblock %}

AppEntrega/templates/AppEntrega/about.html
{% extends "AppEntrega/padre.html" %}


{% load static %}

{% block titulo %} Acerca de {% endblock %}

{% block TituloPrincipal %} Acerca de MILM {% endblock %}

{% block subtitulo %} {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %}

<section id="posts" class="container-md d-flex flex-column  align-items-center justify-content-center min-vh-15">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center mb-5">
                <h1 class="page-title"></h1>
            </div>
        </div>
    
        <div class="row mb-5">
    
            <div class="d-md-flex post-entry-2 half justify-content-center">
                <a href="#" class="me-4 thumbnail">
                    <img src="{% static 'img/about_1.jpg' %}" alt="" class="img-fluid">
                </a>
                <div class="ps-md-5 mt-4 mt-md-0">
                    <h2 class="mb-4 display-4">RECETAS MILM</h2>
                    <p>
                        Recetas MILM surgio como un proyecto de Coderhouse encabezado por el alumno Joaquin Latasa Montenegro, con el objetivo de que personas a lo largo del mundo puedan compartir su cultura y conocimientos gastronomicos.
                        Esperamos que con el paso del tiempo este espacio continue evolucionando y enriqueciendose con una amplia variedad de sabores.
                        Somos muy criticos asi que cada consulta y/o critica que es enviada por el apartado de consultas sera tomada en cuestion con el objetivo de mejorar este sitio.
                        Bienvenidos a Recetas MILM!
                    </p>

        </div>
    
        </div>
    </section>
{% endblock %}

AppEntrega/templates/AppEntrega/agregarAvatar.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Personalización {% endblock %}

{% block TituloPrincipal %} Agrega tu foto de perfil! {% endblock %}

{% block subtitulo %} <form action="" method="POST" enctype="multipart/form-data">{% csrf_token %}

    {{formulario.as_p}}

    <button type="submit">Establecer</button>


</form>
 {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}

AppEntrega/templates/AppEntrega/crearConsulta.html
{% extends "AppEntrega/padre.html" %}


{% load static %}

{% block titulo %} Consultas {% endblock %}

{% block TituloPrincipal %} Consultas {% endblock %}

{% block subtitulo %} Aqui podras consultarnos sobre cualquier duda que tengas, ya sea sobre la pagina o alguna de nuestras recetas! {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %}
<!-- Consultas Section-->
<section class="page-section" id="Consultas">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Consultas</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <!-- Contact Section Form-->
        <div class="row justify-content-center">
            <div class="col-lg-8 col-xl-7">
                <!-- * * * * * * * * * * * * * * *-->
                <!-- * * SB Forms Contact Form * *-->
                <!-- * * * * * * * * * * * * * * *-->
                <!-- This form is pre-integrated with SB Forms.-->
                <!-- To make this form functional, sign up at-->
                <!-- https://startbootstrap.com/solution/contact-forms-->
                <!-- to get an API token!-->
                <form action="/AppEntrega/crearConsulta/" method="POST"> {% csrf_token %}
                    {{formulario}}<br>
                    <input type="submit" value:"Guardar" class="btn btn-primary btn-xl"><br>
                </form><br>
                <a class ="btn btn-primary btn-xl" href="{% url 'Ver mi Consulta' %}">Mostrar mi Consulta</a>

            </div>
        </div>
    </div>
</section>               
{% endblock %}

AppEntrega/templates/AppEntrega/editarPerfil.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Perfil de usuario{% endblock %}

{% block cabecera %} 
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Recetas Milm</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">                       

                    {% if request.user.is_authenticated %}

                    <p style="color: aquamarine;"> {{user.username}}</p>
                    
                    {% with user.avatar_set.last as pfp %}

                    {% if pfp %}

                    <img src="{{pfp.imagen.url}}" alt="No se encuentra la imagen." style="max-width: 90px ;">

                    {% endif %}

                    {% endwith %}

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Avatar' %}">Cambiar Foto de perfil</a></li>    

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Logout' %}">Cerrar Sesión</a></li>    

                    {% else %}      

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'REGISTRO' %}">Registrar</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'LOGIN' %}">Iniciar Sesión</a></li>

                    {% endif %}
                    

                            
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block TituloPrincipal %} Este es tu perfil! {% endblock %}

{% block subtitulo %} 

Aqui puedes editar tu usuario.

{% endblock %}

{% block recetas %} 

<form action="" method="POST">{% csrf_token %}

    {{formulario}}

    <button type="submit">Editar</button>

</form>

{% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}

AppEntrega/templates/AppEntrega/editarSugerencias.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Sugerencias {% endblock %}

{% block TituloPrincipal %} Sugerencias {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %}
<!-- Consultas Section-->
<section class="page-section" id="Consultas">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Aqui podras buscar tus sugerencias</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <form action="/AppEntrega/mis_sugerencias/" method="GET"> 
            <div class="form-floating mb-3">
                <input class="form-control" type="text" name="nombre" placeholder="Nombre" data-sb-validations="required" />
                <label for="name">Nombre</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">Se requiere un nombre.</div>
            </div>
            <input type="submit" value:"Buscar" class="btn btn-primary btn-xl">
        </form>

        <ol>
            {% for sabor in result %}
            <li>

                
                <p>Nombre: {{sabor.nombre}}</p>
                <p>Nombre de la Receta: {{sabor.nombre_receta}}</p>
                <p>Sabor: {{sabor.sabor}}</p>
                <p>Cantidad de pasos: {{sabor.cant_pasos}}</p>
                <p>Dificultad: {{sabor.dificultad}}</p>

                <button>
                    <a href="{% url 'ELiminarSugerencias' sugerencia.nombre %}"> Eliminar Sugerencia</a>
                </button>


            </li>
            {% endfor %}
            </ol>
            </div>
        </div>
    </div>
</section>
{% endblock %}

AppEntrega/templates/AppEntrega/inicio.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Inicio {% endblock %}

{% block TituloPrincipal %} 

 Recetas MILM
 

{% endblock %}

{% block subtitulo %} 


{{mensaje}} 



{% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}

AppEntrega/templates/AppEntrega/login.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Iniciar Sesion {% endblock %}

{% block TituloPrincipal %} Iniciar Sesión {% endblock %}

{% block subtitulo %} <form action="" method="POST">{% csrf_token %}

    {{formulario.as_p}}

    <button type="submit">Iniciar Sesión</button>


</form>
 {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}

AppEntrega/templates/AppEntrega/logout.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Registrarse {% endblock %}

{% block TituloPrincipal %} 

Se ha cerrado sesión

{% endblock %}

{% block subtitulo %} 

{% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}

AppEntrega/templates/AppEntrega/mis_sugerencias.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Sugerencias {% endblock %}
{% block cabecera %} 
<body id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="{% url 'inicio' %}">Recetas Milm</a>
            <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">                       

                    {% if request.user.is_authenticated %}

                    <p style="color: aquamarine;"> {{user.username}}</p>
                    
                    {% with user.avatar_set.last as pfp %}

                    {% if pfp %}

                    <img src="{{pfp.imagen.url}}" alt="No se encuentra la imagen." style="max-width: 90px ;">

                    {% endif %}

                    {% endwith %}

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Crear mi Consulta' %}">Consultas</a></li>        
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Recetas' %}">Recetas</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Hacer Sugerencia' %}">Sugerinos una receta!</a></li>
                    
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Avatar' %}">Cambiar Foto de perfil</a></li>    

                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Logout' %}">Cerrar Sesión</a></li>    

                    {% else %}      
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Crear mi Consulta' %}">Consultas</a></li>        
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Recetas' %}">Recetas</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'Hacer Sugerencia' %}">Sugerinos una receta!</a></li>
                    
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'REGISTRO' %}">Registrar</a></li>
                    <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'LOGIN' %}">Iniciar Sesión</a></li>

                    {% endif %}
                    

                            
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block TituloPrincipal %} Sugerencias {% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %}
<!-- Consultas Section-->
<section class="page-section" id="Consultas">
    <div class="container">
        <!-- Contact Section Heading-->
        <h2 class="page-section-heading text-center text-uppercase text-secondary mb-0">Aqui podras buscar tus sugerencias</h2>
        <!-- Icon Divider-->
        <div class="divider-custom">
            <div class="divider-custom-line"></div>
            <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
            <div class="divider-custom-line"></div>
        </div>
        <form action="/AppEntrega/mis_sugerencias/" method="GET"> 
            <div class="form-floating mb-3">
                <input class="form-control" type="text" name="nombre" placeholder="Nombre" data-sb-validations="required" />
                <label for="name">Nombre</label>
                <div class="invalid-feedback" data-sb-feedback="name:required">Se requiere un nombre.</div>
            </div>
            <input type="submit" value:"Buscar" class="btn btn-primary btn-xl">
        </form>

        <ol>
            {% for sabor in result %}
            <li>
                <p>Nombre: {{sabor.nombre}}</p>
                <p>Nombre de la Receta: {{sabor.nombre_receta}}</p>
                <p>Sabor: {{sabor.sabor}}</p>
                <p>Cantidad de pasos: {{sabor.cant_pasos}}</p>
                <p>Dificultad: {{sabor.dificultad}}</p>
                
            </li>
            {% endfor %}
            
            </ol>

            </div>
        </div>
    </div>
</section>
{% endblock %}

AppEntrega/templates/AppEntrega/registro.html
{% extends "AppEntrega/padre.html" %}

{% load static %}

{% block titulo %} Registrarse {% endblock %}

{% block TituloPrincipal %} 

Registrarse

{% endblock %}

{% block subtitulo %} 

<form action="" method="POST">{% csrf_token %}

    {{formulario.as_p}}

    <button type="submit">Registrarse</button>


</form>

{% endblock %}

{% block recetas %} {% endblock %}

{% block users %} {% endblock %}

{% block Consultas %} {% endblock %}